### ISSUE TITLE
Feedback from my Friends

### ISSUE THREAD

**Issue by UncleHanzi** [Dixin/Etymology#106]
Feedback from my Friends
It makes me feel like a Narcissist, which I am not. 

Too much Uncle Hanzi (Please consider the user who actually wants to learn Chinese)
Horizontal Frame 1 Uncle Hanzi stuff and character input (All the Uncle Hanzi anyone needs to see)
Horizontal Frame 2 Ancient character count (looks like an advertisement). 
Horizontal Frame 3 Character information (This is the important stuff) 
Horizontal Frame 4 Huge Oracle bone picture (just takes up space)
Horizontal Frame 5 Chinese Character Etymology Research OK
Horizontal Frame 6 Huge Uncle Hanzi picture (scroll past)
Horizontal Frame 7 News and Videos OK
Horizontal Frame 8 Huge Uncle Hanzi picture (just takes up space and makes your scrolling finger tired) 
Horizontal Frame 9 WeChat OK
Horizontal Frame 10 Huge Uncle Hanzi picture (just takes up space and makes me feel like a narcisist)
Horizontal Frame 11 Contact OK
Horizontal Frame 12 Donation OK
Horizontal Frame 13 Huge Uncle Hanzi picture (just takes up space and makes your scrolling finger tired)
Horizontal Frame 14 Ann and Dixin OK

**Comment by Dixin** [comment]
The current website is carefully designed based on user study and `telemetry data` in reality.
- For most of the users, the ancient character statistics precisely delivers the entire point of your work.
- The "OK" text blocks are completely ignored by most users. These text blocks work like placeholders and SEO (a cloud of keywords for search engines).
- The "just takes up space" pictures are carefully chosen and carefully retouched to deliver the core information to most users before they go sway quickly - what is ancient character, who you are, how authoritative/recognized you are, and your wechat account to follow.
- I have spend huge mount of time to balance the design and experience between average users and professional users. The overall design does not block or prevent a small number of friends and researchers from searching Chinses characters. They can start to search immediately once opening your website, or start to search from any location of your website.

**Comment by Dixin** [comment]
The current website is carefully designed, not based on personal preference, but based on user study and `telemetry data` in reality.
- For most of the users, the ancient character statistics precisely delivers the entire point/amount/quality of your work. I will add one more item to show you have 12k etymologies, tracked by #103.
- The "OK" text blocks are completely ignored by most users. These text blocks work like placeholders and SEO (a cloud of keywords for search engines).
- The "just takes up space" pictures are carefully chosen and carefully retouched to deliver the core information to most users before they go sway quickly - what is ancient character, who you are, how authoritative/recognized you are, and your wechat account to follow.
- I have spent a huge amount of time to balance the design and experience between average users and professional users. The overall design does not block or prevent a small number of friends and researchers from searching Chinses characters. They can start to search immediately once opening your website, or start to search from any location of your website.
- The overall design is extremely humble in China,
