### ISSUE TITLE
Additional meaning to 和

### ISSUE THREAD

**Issue by burtsevdima** [Dixin/Etymology#114]
It also means And, with

**Comment by UncleHanzi** [comment]
Yes. I first try to put its most original meaning, the one related to the original pictograph. In my next update I will expand on the meanings. Thanks for the comment.

**Comment by Dixin** [comment]
Reopen bug. Let’s close a bug when it’s fix is deployed and verified.

**Comment by UncleHanzi** [comment]
When I give a meaning for a character，up till now, I try to give the original form and the original meaning 本相本意 . It will be a long time before I have extensive descriptions for the meanings of all 15,000 characters.  This should probably be considered an enhancement, not a bug. You will find the same limitations for most characters.

**Comment by Dixin** [comment]
If it is an enhancement, we close the issue when the enhancement is deployed and verified.

**Comment by UncleHanzi** [comment]
Has been corrected in the Etymology file

**Comment by UncleHanzi** [comment]
I think it is OK now.

**Comment by UncleHanzi** [comment]
Made it more clear in latest etymology table.

**Comment by UncleHanzi** [comment]
Fixed in latest etymology table
