### ISSUE TITLE
憾 Usage example is incorrect

### ISSUE THREAD

**Issue by Michaellafone** [Dixin/Etymology#115]
Usage example 用法举例: 震撼 zhèn hàn (shock)

I'm new to your site but I believe the 撼 is incorrect because it does use the 憾

**Comment by UncleHanzi** [comment]
I think it is correct, you may want to check again.

**Comment by Dixin** [comment]
@Michaellafone was right. 

@UncleHanzi You need to look again. I am reopening the issue.
![69EA8D4D-D5CB-4B5E-BABB-1722969EFDFB](https://user-images.githubusercontent.com/1563770/91682382-3a612e80-eb06-11ea-958d-4bc5e12c1413.jpeg)

**Comment by UncleHanzi** [comment]
I fixed this in the etymology table
