### ISSUE TITLE
报错“白”

### ISSUE THREAD

**Issue by xu-chengyuan** [Dixin/Etymology#120]
“白”的说文解字的篆字看似用错了，所用的s05630应该是“锦”

期望数据库中能将字的造字方法(象形，会意，指事，假借，转注，形声)纳入，并可以此分类查询。

**Comment by UncleHanzi** [comment]
This will need to be corrected in the Shuowen file.

**Comment by UncleHanzi** [comment]
I will have to find the correct image and change the number in the Seal or Shuowen table.

**Comment by Dixin** [comment]
Thank you for your feedback. The issue is fixed.
