### ISSUE TITLE
关于汉字简化多对一对问题，以及微信小程序的想法

### ISSUE THREAD

**Issue by mr-circle** [Dixin/Etymology#126]
汉字爷爷您好：
我在大概十年前就关注过您的网站，那时候您的词源网站上面的文字还都是图片格式的，无法无损放大。现在再去看的时候，它已经变成了base64的格式，看到这些变化，我太为您开心了，也看到了网站的很多其他变化，这都让人欣喜。
我一直都喜欢汉字，尤其是汉字的起源和演变，之前也师从李传声先生治过一些印。最近学习书法，也学习汉字演变以及汉字起源和简化，也同时这学习写代码，都是门外汉哈。在这些过程里，当然免不了来您的汉字字源网学习。
不过，在学习过程中我发现一处问题，就是汉字简化中多对一的时候的问题。比如繁体字的”裡“和”裏“和”里“全都是简化成来“里”，那么，如果我们搜索“里”的时候，应该注明它的对应的繁体字有”裡“和”裏“和”里“，当然，”裡“和”裏“是一样的，只不过写法不一样而已，但是，里自己也是在繁体里面就存在的，用于里程，故里，还有姓氏。同样的情况除了“里”还有很多，而这个在您的网站上面并没有体现出来，我觉得这个很重要，否则容易误导别人，希望能够得到改进。
另外，基于手机的普及，和微信小程序的便捷，我本来打算做一个汉字起源的小程序，以及汉字简化多对一的小程序用来给我们大陆人学习繁体字。然后我就想到了您的字源网，所以我就想把这个想法和您说，如果您觉得可行，我可以在您的授权之后去开发这个小程序，从而帮助到更多的人去学习汉字的起源。
以上，是我的一些建议和想法，期待您的回复。
圆圈yuan-quan@live.cn

**Comment by Dixin** [comment]
Thank you for your feedback. I searched 里, the result is accurate:
![image](https://user-images.githubusercontent.com/1563770/99855731-50e2b900-2b3c-11eb-801b-570037cfc450.png)

Another example is 台:
![image](https://user-images.githubusercontent.com/1563770/99855676-31e42700-2b3c-11eb-8bc9-90c1ead1d2aa.png)
