### ISSUE TITLE
I want to know the reason about 西 which come from oil.

### ISSUE THREAD

**Issue by Chang1973** [Dixin/Etymology#127]
If you have an issue with the website, please describe what is the issue, and how to reproduce the issue.

If you found an issue with etymology, please describe what is the Chinese character, and what is the issue or what is missing with the character or its etymology.

If you want a new feature, please describe how it works.
我认为 醫 中的 西 应该是指酒，而不是油。如果我说的不对，请指正。

**Comment by UncleHanzi** [comment]
In my standard decomposition of characters, I try to have a standard single name for each component that describes best its meaning in every case. 
I do not want to refer to 人 as “person” one place and “man” in another place. 
酉 is a jug, which may contain many things.  
One standard name will not always be an accurate description, but that is how my decomposition works. 
The name was oil-jug-you. I have changed the name to container-jug, which may be more accurate in most cases. 
The standard names will never be perfect.  
Name changed in etymology file.
