### ISSUE TITLE
Eve Kushner issue

### ISSUE THREAD

**Issue by UncleHanzi** [Dixin/Etymology#130]
One of my long term users Eve Kushner can not access my web site. 
I told her to delete cookies, and she still cant. 
She is using Chrome from the U.S. 
She is on facebook

In Chrome I input 隙. I get this error msg:

Error: [404 error] Not Found. Please refresh the page and try again.
出错了, 请刷新页面, 或清空浏览器cookie并重启浏览器后重试.

**Comment by Dixin** [comment]
What are the repro steps?

If she is not a technical person, she can simply record a video with her cellphone.

**Comment by UncleHanzi** [comment]
This was a problem caused by a security fix in Chrome. Eve says it works now.
