### ISSUE TITLE
Regression of 系

### ISSUE THREAD

**Issue by Dixin** [Dixin/Etymology#136]
Previous release vs. current release.
![screencapture-localhost-50518-2020-09-09-20_32_35](https://user-images.githubusercontent.com/1563770/92679222-b0bb1900-f2dc-11ea-9e40-adf37232ad9a.jpg)

**Comment by UncleHanzi** [comment]
Here is the new table. 
[EtyTable09112020.zip](https://github.com/Dixin/Etymology/files/5205876/EtyTable09112020.zip)
