### ISSUE TITLE
山 character doesn’t showany etymology 

### ISSUE THREAD

**Issue by mixmac** [Dixin/Etymology#137]
https://hanziyuan.net/#山
the following error message appears with an iphone xs / ios 13.6.1 / safari mobile when searching for the 山 character

Error: [404 error] Not Found. Please refresh the page, or cleanup browser cookies and restart browser and try again, or use a different browser.
出错了, 请刷新页面, 或清空浏览器cookie并重启浏览器后重试, 或换用其他浏览器. Report issue 报错/留言

**Comment by Dixin** [comment]
Cannot reproduce the issue. What browser do you use?

![image](https://user-images.githubusercontent.com/1563770/93411126-4d3a6980-f84f-11ea-8f8a-22d4edcdc710.png)

**Comment by mixmac** [comment]
as written above, my mobile device has the following configuration:
iphone Xs / ios 13.6.1 / safari mobile
![image](https://user-images.githubusercontent.com/6203952/93464057-df428080-f8e8-11ea-96d1-12b3cec30db6.png)

the problem doesn't appear with firefox mobile.

**Comment by Dixin** [comment]
The website is now working on iOS with Chrome, Safari, Firefox. Thank you for your feedback! Please let me know if you have any issues.
