### ISSUE TITLE
New structure for Chinese character information table 

### ISSUE THREAD

**Issue by UncleHanzi** [Dixin/Etymology#52]
Normalized Chinese Character Information Table   

Input Character 
If in T_Old print information else 
If in T_Char print information else 
If in S_Char print information else 
Character not analyzed yet.  

If a column has “z” or blank, it means it is not applicable and should not be printed. 

S_Char – Simplified character
S_Rule – Simplification Rule - how to simplify the written forms of traditiopnal characters
S_Info – Explanation of Simplification Rule    (needs work)
S_Number – Official simplified character number 0001 to 8105 
S_Different – Simplified character different from traditional character “y” or “n”
S_New – Simplification results in new character not in Kangxi dictionary  “y” or “n”
J_Char – Japanese Kanji if different.
V_Rule  - Variant Rule – Which variants are banned, which are allowed
V_Info – Explanation of Variant Rule 
Font_Rule – Font Rule - New character form 新字體 (basically a font difference between Taiwan and China different code points)
C_Rule – When one or more S_Rule or V_Rules apply (needs work)
T_Char – Traditional character
T_Old – Older forms and alternates of the traditional character
Mean_Original – Original Meaning 
Mean_Modern – Modern Meaning 
Mean_Compound – Compound character example and meaning. 
Pinyin_1 – Main pinyin pronunciation
Pinyin_n -  Other pinyin pronunciations
Ety_Standard – Standard Etymological Explanation. 
Ety_Name - Standard Etymological Name
Ety_Explanation – Further explanation if necessary

Other columns not currently used begin with either z or x.

**Comment by UncleHanzi** [comment]
The new table in Etymology
It should be good. 
The query for duplicates does notrecognize Extension B Unicode.
[Ety040520181.zip](https://github.com/Dixin/Etymology/files/1885895/Ety040520181.zip)

**Comment by UncleHanzi** [comment]
This is the create script for the new etymology table
[Etymology.zip](https://github.com/Dixin/Etymology/files/1900604/Etymology.zip)

**Comment by UncleHanzi** [comment]
This is the Access database with the Etymology Table
[Ety040520181.zip](https://github.com/Dixin/Etymology/files/1900620/Ety040520181.zip)

**Comment by UncleHanzi** [comment]
[Ety04142019.zip](https://github.com/Dixin/Etymology/files/1909914/Ety04142019.zip)

**Comment by Dixin** [comment]
Duplication of #60.
