### ISSUE TITLE
Vector files ?

### ISSUE THREAD

**Issue by hugolpz** [Dixin/Etymology#59]
Do you have vector files ?
If not, Wikipedia users made a script including `potrace` command which convert into svg, then uploaded images to wikimedia commons (we got the agreement from Richards back in 2008). I think with some digging it would be possible for you to get the core command, and run it on your images to to provide vector versions. 

- [Conversion using potrace](https://commons.wikimedia.org/wiki/Commons:Ancient_Chinese_characters_project/Tutorial#Conversion_using_potrace) > [Commons:Ancient_Chinese_characters:Linux_tutorial](https://commons.wikimedia.org/wiki/Commons:Ancient_Chinese_characters:Linux_tutorial)

The script converts to svg, and upload the file to Wikimedia Commons with the proper license and tag.

The project was initially started to help Hanzi Shushu, but my brother and me failed (2008), and some wikipedian succeeded in June 2016 or 2017, but did not ping you about it. I'am here to correct it :+1:

**Comment by Dixin** [comment]
Thank you for your feedback. This work is on our plate.

**Comment by Dixin** [comment]
Fixed with commit ee7ed86.
