### ISSUE TITLE
Updating Image Files

### ISSUE THREAD

**Issue by UncleHanzi** [Dixin/Etymology#61]
Image Tables 
Currently all my images are stored in SQL tables

1) Oracle characters, 
2) Bronze characters, 
3) LST characters and 
4) Shuowen Seal characters. 
These characters are currently in reasonable shape, but I will need the ability to update them with new character information eventually. 
Conversion to SVG
I scanned all my 100,000 images back in the 1990s when I could only scan them at 300 dpi
Converting them using a batch program to SVG causes some problems. Sometimes it works, but sometimes, the resolution is such that the characters are distorted and unusable by the conversion algorithm. 
Updating the image files
In the 1990s I used the best books at the time which ranged from 1959 to 1985
Occasionally I find mistakes which need to be corrected, but also,
Since then, better books have been written on bronze characters and oracle characters. 
At some point in the future I will want to scan these new books at higher resolution, and input the newer images and analysis into  and the image tables. 
These books were written in the early 2000s

**Comment by Dixin** [comment]
The process:
1. Convert the .gif files to .svg files.
2. Review the .svg files with .gif files side by side.
3. Upload the .svg files to the database with a script.
4. Update the .svg files in the database in the future.

**Comment by Dixin** [comment]
Fixed with commit ee7ed86f20bb5850294a5e99c3382a32d48d0fda.
