### ISSUE TITLE
Unicode range validation test: 

### ISSUE THREAD

**Issue by UncleHanzi** [Dixin/Etymology#82]
Unicode range validation test: 

All these ranges contain legitimate Chinese characters which may appear in the Etymology table. Following are test characters from each range.

一 CJK Unified Ideograms Unified Ideographs: (U+4E00 to U+9FFF)
㐦 CJK Ideographs Extension A: (U+3400 to U+4DBF)
𠀀  CJK Ideographs Extension B: (U+20000 to U+2A6DF)
𪜀  CJK Ideographs Extension C: (U+2A700 to U+2B73F)
𫝀  CJK Ideographs Extension D: (U+2B740 to U+2B81F)
“丽” CJK Comparability Ideographs Supplement: (U+2F800 to U+2FA1F)
⺀ CJK Radicals Supplement: (U+2E80 to U+2EFF)
 ⼀  Kangxi Radicals: (U+2F00 to U+2FDF) 
“⿰” Ideographic Description Characters: (U+2FF0 to U+2FFF)
〥 CJK Symbols and Punctuation: (U+3000 to U+303F)
い Hiragana: (U+3040 to U+309F)
ア Katakana: (U+30A0 to U+30FF)
ㄆ Bopomofo: (U+3100 to U+312F)
ㆡ Bopomofo Extended: (U+31A0 to U+31BF)
㇏ CJK Strokes: (U+31C0 to U+31EF) Legitimize 
ㇰ Katakana Phonetic Extensions: (U+31F0 to U+31FF) 
豈 CJK Compatibility Ideographs: (U+F900 to U+FAFF)
︽ CJK Compatibility Forms: (U+FE30 to U+FE4F)
ｬ Half width and Full width Forms: (U+FF00 to U+FFEF)

**Comment by UncleHanzi** [comment]
I do not have all of these test characters in all of these code ranges, I am just saying that each of these code ranges may have legitimate characters that are now or may in the future be in my table.

**Comment by Dixin** [comment]
Closed by c2cbc9020d1e9342a72b490cf8fea525615a46b2.

**Comment by Dixin** [comment]
Closed by 5e53e4cc617f9cf8f8267ece8168411057d6118a.
