### ISSUE TITLE
Unicode Extension E and F

### ISSUE THREAD

**Issue by UncleHanzi** [Dixin/Etymology#99]
Case 36, 𫢸 CJK Ideographs Extension E: (U+2B820..U+2CEAF) 
My browser can show some extension D characters
Found 107 characters from the 2013 standard here
They are simplified characters of some traditional characters

Case 37, “𬺰”  CJK Ideographs Extension F: (U+2CEB0..U+2EBEF) 
My browser can show no extension F characters but the code points are still part of the Unicode standard

**Comment by Dixin** [comment]
Display extension F.
